(async()=>{let checks=0;function check(ok,label){checks++;if(!ok)throw Error(label);}
try{
const old={stars:32,lastDay:'2026-09-24',streak:8,sound:false};localStorage.setItem(STORAGE_KEY,JSON.stringify(old));progressData=loadProgress();check(progressData.stars===32&&progressData.streak===8&&progressData.lastDay===old.lastDay,'legacy');check(progressData.enabled.join()==='true,true,false,false,false'&&progressData.stats.plays===0,'new defaults');saveProgress();progressData=loadProgress();check(progressData.stars===32,'migration roundtrip');
showScreen('home');startGame(3);check(screen==='home','locked guard');renderSettings();const toggles=[...document.querySelectorAll('#level-settings input')];toggles.forEach(toggle=>{toggle.checked=true;toggle.dispatchEvent(new Event('change'));});check(loadProgress().enabled.every(Boolean),'settings saved');
for(const level of levels){for(let j=0;j<30;j++){const qs=createQuestions(level.mode,level.limit);check(qs.length===10&&new Set(qs.map(q=>`${q.a},${q.op},${q.b}`)).size===10,'unique');check(qs.every(q=>q.a>=0&&q.a<=level.limit&&q.b>=0&&q.b<=level.limit&&q.answer>=0&&q.answer<=level.limit&&q.answer===(q.op==='addition'?q.a+q.b:q.a-q.b)),'bounds');if(level.id===5)check(qs.filter(q=>q.op==='addition').length===5,'balanced');}
for(const target of [0,5,8,10]){const before={...progressData.stats};const stars=progressData.stars;startGame(level.id);enterDigit('2');enterDigit('0');check(input==='20','input 20');editInput(false);check(input==='2','backspace');editInput(true);
for(let i=0;i<10;i++){if(i>=target){enterDigit('9');enterDigit('9');checkAnswer();checkAnswer();check(!solved,'retry');}String(questions[i].answer).split('').forEach(enterDigit);checkAnswer();check(solved,'solved');checkAnswer();nextQuestion();}
check(screen==='result'&&firstTryCorrect===target,'result');check(progressData.stats.plays===before.plays+1&&progressData.stats.answered===before.answered+10&&progressData.stats.correct===before.correct+target,'stats');check(progressData.stars===stars+earnedStars(target),'award');check(progressData.cleared.includes(level.id),'cleared');check(byId('score').textContent==='きょうも ひとつ つよくなったね！','positive');const after=progressData.stars;nextQuestion();check(progressData.stars===after,'no duplicate');byId('again').click();check(activeLevel===level.id&&questionIndex===0,'same level replay');}}
check(progressData.recent.length===60,'bounded history');renderHome();check([...document.querySelectorAll('#level-cards .level-card small')].every(el=>el.textContent.includes('クリア')),'all marks');renderSettings();check(byId('learning-stats').textContent.includes(String(progressData.stats.answered)),'parent stats');
progressData.learning=freshLearning();progressData.recent=Array.from({length:10},()=>({type:'addition-cross',correct:false}));let adapted=0,baseline=0;for(let i=0;i<300;i++)adapted+=createQuestions('addition',20).filter(q=>calculationType(q)==='addition-cross').length;progressData.recent=[];for(let i=0;i<300;i++)baseline+=createQuestions('addition',20).filter(q=>calculationType(q)==='addition-cross').length;check(adapted>baseline&&adapted-baseline<650,'gentle bias');
check(calculationType({a:8,b:7,answer:15,op:'addition'})==='addition-cross','carry');check(calculationType({a:13,b:8,answer:5,op:'subtraction'})==='subtraction-cross','borrow');
progressData.lastDay='2026-01-31';progressData.streak=3;firstTryCorrect=0;awardCompletion(new Date(2026,1,1));check(progressData.streak===4,'next day');awardCompletion(new Date(2026,1,1));check(progressData.streak===4,'same day');awardCompletion(new Date(2026,1,3));check(progressData.streak===1,'gap');
const beforeReset=progressData.stars;byId('reset-request').click();byId('reset-cancel').click();check(progressData.stars===beforeReset,'cancel');byId('reset-request').click();byId('reset-confirm-button').click();check(progressData.stars===0&&progressData.recent.length===0&&progressData.cleared.length===0&&progressData.stats.answered===0&&progressData.enabled.every(Boolean),'full reset preserve settings');
progressData.enabled.fill(false);renderHome();check([...document.querySelectorAll('#level-cards .level-card')].every(el=>el.disabled)&&!byId('levels-empty').hidden,'all off');
localStorage.setItem(STORAGE_KEY,JSON.stringify({...old,enabled:[false,'bad'],stats:{correct:90,answered:3},recent:[null,{type:'bad',correct:false}],cleared:[1,1,9]}));progressData=loadProgress();check(progressData.stars===32&&progressData.stats.correct===3&&progressData.recent.length===0&&progressData.cleared.join()==='1','sanitize');
const setItem=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('blocked');};saveProgress();check(!byId('storage-notice').hidden,'blocked storage');Storage.prototype.setItem=setItem;
showScreen('result');firstTryCorrect=10;showReward();check(byId('confetti').children.length===28,'confetti');await new Promise(r=>setTimeout(r,3700));check(byId('confetti').children.length===0,'cleanup');const media=window.matchMedia;window.matchMedia=()=>({matches:true});showReward();check(byId('confetti').children.length===0,'reduced');window.matchMedia=media;
for(const view of ['home','settings','collection','result']){renderCollection();showScreen(view);check(document.documentElement.scrollWidth<=innerWidth,'viewport '+view);}
localStorage.setItem(STORAGE_KEY,JSON.stringify(old));

const legacy={...freshProgress(),stars:37,streak:4,lastDay:'2026-09-24',stats:{plays:8,answered:73,correct:61},recent:[{type:'addition-cross',correct:false}],cleared:[1,3]};delete legacy.clock;
localStorage.setItem(STORAGE_KEY,JSON.stringify(legacy));progressData=loadProgress();check(progressData.stars===37&&progressData.stats.correct===61&&progressData.recent.length===1&&progressData.cleared.join()==='1,3','v3 migration');check(progressData.clock.enabled.join()==='true,false'&&!progressData.clock.medal,'clock defaults');saveProgress();progressData=loadProgress();check(progressData.streak===4,'legacy saved intact');
showScreen('home');startClock(2);check(screen==='home','clock lock');renderSettings();const halfToggle=document.querySelectorAll('#clock-settings input')[1];halfToggle.click();check(loadProgress().clock.enabled[1],'half enabled persisted');
for(let hour=1;hour<=12;hour++)for(const minute of [0,30]){drawClock(hour,minute);check(byId('clock-face').querySelectorAll('text').length===12,'12 numerals');check(byId('clock-face').querySelector('[data-hand="hour"]').getAttribute('transform')===`rotate(${hour%12*30+minute*.5} 150 150)`,'hour angle');check(byId('clock-face').querySelector('[data-hand="minute"]').getAttribute('transform')===`rotate(${minute*6} 150 150)`,'minute angle');}
const mathBefore=JSON.stringify({stats:progressData.stats,recent:progressData.recent,cleared:progressData.cleared});
for(const level of clockLevels)for(const target of [0,5,8,10]){
const before={...progressData.clock.stats};const stars=progressData.stars;const errors=progressData.clock.errors[level.type];const hadMedal=progressData.clock.medal;
startClock(level.id);check(new Set(questions.map(q=>q.answer)).size===10&&questions.every(q=>q.minute===level.minutes[0]),'unique clock times');check(byId('keypad').hidden&&byId('check').hidden&&!byId('clock-question').hidden,'clock controls');
enterDigit('1');check(input==='','no text input');
for(let i=0;i<10;i++){const buttons=[...document.querySelectorAll('#clock-choices button')];check(buttons.length===3&&new Set(buttons.map(b=>b.dataset.answer)).size===3,'three unique choices');if(i>=target){buttons.find(b=>Number(b.dataset.answer)!==questions[i].answer).click();check(!solved&&byId('feedback').textContent==='もういちど よくみてみよう！','gentle clock retry');}buttons.find(b=>Number(b.dataset.answer)===questions[i].answer).click();check(solved&&byId('clock-face').classList.contains('clock-success'),'sparkle');nextQuestion();}
check(screen==='result'&&byId('score').textContent.includes('とけいマスター'),'clock result');check(progressData.stars===stars+earnedStars(target),'clock stars');check(progressData.clock.stats.plays===before.plays+1&&progressData.clock.stats.answered===before.answered+10&&progressData.clock.stats.correct===before.correct+target,'clock stats');check(progressData.clock.errors[level.type]===errors+10-target,'clock errors');check(progressData.clock.medal&&loadProgress().clock.medal,'medal saved');check(byId('new-friends').textContent.includes('とけいメダル')===!hadMedal,'first medal only');check(JSON.stringify({stats:progressData.stats,recent:progressData.recent,cleared:progressData.cleared})===mathBefore,'math history unchanged');const awarded=progressData.stars;nextQuestion();check(progressData.stars===awarded,'clock no duplicate award');byId('again').click();check(gameKind==='clock'&&activeLevel===level.id&&questionIndex===0,'clock replay');}
renderCollection();check(byId('collection-grid').children.length===6&&byId('collection-grid').textContent.includes('とけいマスター'),'medal collection');renderSettings();check(byId('clock-trends').textContent.includes('15問')||byId('clock-trends').textContent.includes('17問'),'clock parent errors');
progressData.enabled[0]=true;startGame(1);check(gameKind==='math'&&byId('clock-question').hidden&&!byId('keypad').hidden&&!byId('check').hidden,'return to math');
startClock(2);check(document.documentElement.scrollWidth<=innerWidth,'clock width');check(byId('clock-face').getBoundingClientRect().width<=innerWidth,'clock size');
byId('reset-request').click();byId('reset-confirm-button').click();check(!progressData.clock.medal&&progressData.clock.stats.plays===0&&progressData.clock.enabled[1],'reset clock retains settings');

await testLearning(check);
document.head.querySelector('style').remove();document.body.textContent='PASS '+checks+' checks. Legacy migration, 5 levels, bounds, mixed balance, retry, stats, adaptive selection, settings, collections, streaks, replay, reset, responsive layout. Bias counts '+adapted+'/'+baseline;
}catch(e){document.head.querySelector('style')?.remove();document.body.textContent='FAIL '+e.stack;}})();
